### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by losgranos** [analogcode/Swift-Radio-Pro#105] opened 2018-11-30 15:13 UTC
I'm getting a couple of these "Using '!' here is deprecated and will be removed in a future release" any way i can rid of these?

thanks in advance
juan

**Comment by fethica** [comment] 2018-11-30 15:42
Hey @losgranos, did you check if the issue is present on the dev branch? Thanks.

**Comment by losgranos** [comment] 2018-11-30 15:51
@fethica i started with fresh file, just downloaded it from the master... should I be using a diffrent one?

**Comment by fethica** [comment] 2018-11-30 15:59
@losgranos Yes try the dev branch instead, it's the most recent code, not merged to master yet since iOS 9 will no longer be supported.

**Comment by losgranos** [comment] 2018-11-30 16:00
Ah ok, of course that makes sense... totally forgot! thanks!

**Closed** 2018-11-30 16:15 UTC
